### PR TITLE
Fixes for #10 and #11

### LINKED ISSUE #10: Board.get_threads(page=1) raises requests.exceptions.MissingSchema
Not sure why this is happening, but it seems to me that somewhere between calling get_threads(page=1) and the exception occurring some method or function should use self._url of the calling Board instance to create the correct API request URL for the first page, instead the raw page integer value is somehow forwarded to requests which raises this error.

### LINKED ISSUE #11: Fetching board metadata always results in a TypeError
When accessing any property of a Board instance that uses the _get_metadata method a TypeError is raised. This is because in _fetch_boards_metadata the function tries to use the Url class' board_list method -- and while it is marked as a staticmethod it still expects the self-argument, which will never be provided by the calling code.

### PR DESCRIPTION
**Pull request by irlittz**
Fixes #10 and #11.

### CODE REVIEW

**Comment by DanielOaks** [comment]
Looks like it should be fine, you've tested this and it all works?

**Comment by irlittz** [comment]
I did really simple tests with get_threads and different pages which all worked. Fetching board metadata through any of the Board's properties works too. You might want to look at [this](https://github.com/irlittz/BASC-py4chan/commit/ddfa9bf53f58727a8be62cdcbca677464d62da6d?diff=unified#diff-d48122fb5bdc905a09a6735346e708baR63), it's how I determine if SSL should be used or not. This is a problem when functions outside of the Board class attempt to use _fetch_board_metadata, you end up having to create a dummy URL generator instance without a valid board name (which does work).

**Comment by DanielOaks** [comment]
Cool, I've tested with BASC-Archiver and it all seems to work fine.

Thanks a bunch for the fixes, I've pulled this in (with some rebasing to avoid messy merge commits), your code's in master now! I'll try to push an update to pypi with it tonight.

**Comment by irlittz** [comment]
Great, sounds awesome.

**Comment by irlittz** [comment]
Actually I just noticed. I'm sorry, I wasn't entirely clear on why you did something in the previous code. You want to re-add the line: ```if not _metadata:``` [here](https://github.com/bibanon/BASC-py4chan/blob/master/basc_py4chan/board.py#L31).

**Pull request closed without merging**
