### PR TITLE
Fix Board object creation

### PR DESCRIPTION
**Pull request by nattycleopatra**
This broke with commit 5daafa9292fb5719db043f6c599cb6b58d4fcb4c changing up the variable name back in January. (Please be careful)

### CODE REVIEW

**Comment by antonizoon** [comment]
Oh dear. We'll watch out next time.

**Comment by DanielOaks** [comment]
Is this fix pushed into a new release? If not I can create and push a new release.

**Comment by nattycleopatra** [comment]
It happened after 0.6.0 so no harm done really, but a new minor release would be cool unless it's too early.

**Comment by nattycleopatra** [comment]
Actually I noticed this has to be corrected other places as well, give me a minute.

**Comment by DanielOaks** [comment]
Yeah, we'll probably look at setting up some proper tests (and using them through Travis-CI or similar), to make sure regressions and breakages like this don't happen. And release `1.0.0` once we're happy with it, go to SemVer proper!

**Pull request merged**
